spring:
  datasource:
    url: "jdbc:postgresql://89.223.94.132:5432/jobsite"
    username: "nutrymaco"
    password: "Wtkv7GERgerghrt"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate.ddl-auto: "create-drop"

  redis:
    host: "89.223.94.132"
    port: 6379
    password: "eqrg132n2Xn12"


logging:
  file:
    name: "logs/info.log"

search:
  title-boost: 10
  prefix-length: 2

autocomplete:
  host: "http://89.223.94.132"
  port: 7299

elastic:
  host: "89.223.94.132"
  port: 9200
  create-index: false